-- Create table to store the notification user in history
DROP TABLE IF EXISTS signalement_workflow_notification_user_value;
CREATE TABLE signalement_workflow_notification_user_value
(
  id_history integer NOT NULL DEFAULT 0,
  id_task integer NOT NULL,
  notification_value text,
  CONSTRAINT signalement_workflow_notification_user_value_pkey PRIMARY KEY (id_history, id_task),
  CONSTRAINT fk_notification_user_value_id_history FOREIGN KEY (id_history)
      REFERENCES workflow_resource_history (id_history) MATCH SIMPLE
      ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_notification_user_id_task FOREIGN KEY (id_task)
      REFERENCES workflow_task (id_task) MATCH SIMPLE
      ON UPDATE RESTRICT ON DELETE RESTRICT
);


-- Add the title of the notification in history
ALTER TABLE signalement_workflow_notification_user_config ADD COLUMN title character varying(255);

UPDATE signalement_workflow_notification_user_config SET title='Message à destination de l''usager' WHERE id_task=76;
UPDATE signalement_workflow_notification_user_config SET title='Message à destination de l''usager' WHERE id_task=77;


-- CHANGE THE TASK NOTIFICATION USER SIGNALEMENT 
-- delete the message column from signalement_workflow_notification_user_config
ALTER TABLE signalement_workflow_notification_user_config DROP COLUMN message;

-- add the foreign key in the signalement_workflow_notification_user_config table
ALTER TABLE signalement_workflow_notification_user_config ADD COLUMN id_message INTEGER;

ALTER TABLE signalement_workflow_notification_user_config
ADD CONSTRAINT signalement_workflow_notification_user_config_fkey
FOREIGN KEY (id_message)
REFERENCES signalement_message_creation(id_message);


-- add the references to the message in signalement_workflow_notification_user_config
UPDATE signalement_workflow_notification_user_config SET id_message=1 WHERE id_task=76;
UPDATE signalement_workflow_notification_user_config SET id_message=1 WHERE id_task=77;

-- add the config table for NotificationSignalementUser3ContentsTask
DROP TABLE IF EXISTS signalement_workflow_notifuser_3contents_config;
CREATE TABLE signalement_workflow_notifuser_3contents_config
(
  id_task integer NOT NULL,
  subject character varying(255),
  sender character varying(255),
  message1 text,
  message2 text,
  message3 text,
  CONSTRAINT signalement_workflow_notifuser_3contents_config_pkey PRIMARY KEY (id_task)
);


-- add the value table for NotificationSignalementUser3ContentsTask
DROP TABLE IF EXISTS signalement_workflow_notifuser_3contents_value;
CREATE TABLE signalement_workflow_notifuser_3contents_value
(
  id_history integer NOT NULL DEFAULT 0,
  id_task integer NOT NULL,
  notification_value text,
  CONSTRAINT signalement_workflow_notifuser_3contents_value_pkey PRIMARY KEY (id_history, id_task),
  CONSTRAINT fk_notifuser_3contents_value_id_history FOREIGN KEY (id_history)
      REFERENCES workflow_resource_history (id_history) MATCH SIMPLE
      ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_notification_user_id_task FOREIGN KEY (id_task)
      REFERENCES workflow_task (id_task) MATCH SIMPLE
      ON UPDATE RESTRICT ON DELETE RESTRICT
);

-- Add the task notification (3contents) to programmer, reprogrammer, service fait and rejeter actions
-- programmer
INSERT INTO workflow_task(id_task,task_type_key,id_action) VALUES (80,'taskSignalementUserNotification3Contents',17);
INSERT INTO workflow_task(id_task,task_type_key,id_action) VALUES (81,'taskSignalementUserNotification3Contents',46);
INSERT INTO workflow_task(id_task,task_type_key,id_action) VALUES (82,'taskSignalementUserNotification3Contents',52);
INSERT INTO workflow_task(id_task,task_type_key,id_action) VALUES (83,'taskSignalementUserNotification3Contents',40);
-- reprogrammer
INSERT INTO workflow_task(id_task,task_type_key,id_action) VALUES (84,'taskSignalementUserNotification3Contents',29);
-- service fait
INSERT INTO workflow_task(id_task,task_type_key,id_action) VALUES (85,'taskSignalementUserNotification3Contents',18);
INSERT INTO workflow_task(id_task,task_type_key,id_action) VALUES (86,'taskSignalementUserNotification3Contents',22);
INSERT INTO workflow_task(id_task,task_type_key,id_action) VALUES (87,'taskSignalementUserNotification3Contents',41);
INSERT INTO workflow_task(id_task,task_type_key,id_action) VALUES (88,'taskSignalementUserNotification3Contents',49);
INSERT INTO workflow_task(id_task,task_type_key,id_action) VALUES (89,'taskSignalementUserNotification3Contents',53);
-- rejeter
INSERT INTO workflow_task(id_task,task_type_key,id_action) VALUES (90,'taskSignalementUserNotification3Contents',16);
INSERT INTO workflow_task(id_task,task_type_key,id_action) VALUES (91,'taskSignalementUserNotification3Contents',21);

-- init the messages
-- programmer
INSERT INTO signalement_workflow_notifuser_3contents_config(id_task,subject,sender,message1,message2,message3) VALUES(80,'Signalement d''un incident','Mairie de Paris','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>');
INSERT INTO signalement_workflow_notifuser_3contents_config(id_task,subject,sender,message1,message2,message3) VALUES(81,'Signalement d''un incident','Mairie de Paris','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>');
INSERT INTO signalement_workflow_notifuser_3contents_config(id_task,subject,sender,message1,message2,message3) VALUES(82,'Signalement d''un incident','Mairie de Paris','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>');
INSERT INTO signalement_workflow_notifuser_3contents_config(id_task,subject,sender,message1,message2,message3) VALUES(83,'Signalement d''un incident','Mairie de Paris','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>');
-- reprogrammer
INSERT INTO signalement_workflow_notifuser_3contents_config(id_task,subject,sender,message1,message2,message3) VALUES(84,'Signalement d''un incident','Mairie de Paris','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message a été pris en compte.<br />Les services municipaux vont mettre en oeuvre d''ici le [Date de traitement prévue] les actions appropriées.<br />Merci de l''intérêt que vous portez à l''espace public parisien.</p><br /><p>La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>');
-- service fait
INSERT INTO signalement_workflow_notifuser_3contents_config(id_task,subject,sender,message1,message2,message3) VALUES(85,'Signalement d''un incident','Mairie de Paris','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>');
INSERT INTO signalement_workflow_notifuser_3contents_config(id_task,subject,sender,message1,message2,message3) VALUES(86,'Signalement d''un incident','Mairie de Paris','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>');
INSERT INTO signalement_workflow_notifuser_3contents_config(id_task,subject,sender,message1,message2,message3) VALUES(87,'Signalement d''un incident','Mairie de Paris','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>');
INSERT INTO signalement_workflow_notifuser_3contents_config(id_task,subject,sender,message1,message2,message3) VALUES(88,'Signalement d''un incident','Mairie de Paris','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>');
INSERT INTO signalement_workflow_notifuser_3contents_config(id_task,subject,sender,message1,message2,message3) VALUES(89,'Signalement d''un incident','Mairie de Paris','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>','<p>Votre message est clôturé.<br />Les services municipaux ont traité votre message et ont opéré les actions appropriées.<br />Nous vous remercions une nouvelle fois de votre participation qui a permis d''améliorer la qualité de notre environnement urbain.</p><p><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public</p>');
-- rejeter
INSERT INTO signalement_workflow_notifuser_3contents_config(id_task,subject,sender,message1,message2,message3) VALUES(90,'Signalement d''un incident','Mairie de Paris','<p>Nous avons bien reçu votre message mais les informations transmises sont insuffisantes ou inadaptées<br />et ne permettent pas à nos services d''y donner suite.<br />Avant de ne nous transmettre un nouveau message, nous vous invitons à vérifier si :<br /><br />- La localisation transmise est bien précise, en particulier dans un grand parc.<br />- L''incident se situe bien sur l''espace public municipal et non dans un espace privé.<br />- La description de la situation est précise.<br />- La qualité de la photo est correcte et adaptée.<br />- Une signalétique explicative n''est pas déjà mise en place autour de l''incident.<br />Ceci afin de nous permettre d''améliorer notre réactivité et de vous apporter toute satisfaction dans notre réponse.<br /><br />Nous vous remercions de votre participation.<br /><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public<br /></p>','<p>Nous avons bien reçu votre message mais les informations transmises sont insuffisantes ou inadaptées<br />et ne permettent pas à nos services d''y donner suite.<br />Avant de ne nous transmettre un nouveau message, nous vous invitons à vérifier si :<br /><br />- La localisation transmise est bien précise, en particulier dans un grand parc.<br />- L''incident se situe bien sur l''espace public municipal et non dans un espace privé.<br />- La description de la situation est précise.<br />- La qualité de la photo est correcte et adaptée.<br />- Une signalétique explicative n''est pas déjà mise en place autour de l''incident.<br />Ceci afin de nous permettre d''améliorer notre réactivité et de vous apporter toute satisfaction dans notre réponse.<br /><br />Nous vous remercions de votre participation.<br /><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public<br /></p>','<p>Nous avons bien reçu votre message mais les informations transmises sont insuffisantes ou inadaptées<br />et ne permettent pas à nos services d''y donner suite.<br />Avant de ne nous transmettre un nouveau message, nous vous invitons à vérifier si :<br /><br />- La localisation transmise est bien précise, en particulier dans un grand parc.<br />- L''incident se situe bien sur l''espace public municipal et non dans un espace privé.<br />- La description de la situation est précise.<br />- La qualité de la photo est correcte et adaptée.<br />- Une signalétique explicative n''est pas déjà mise en place autour de l''incident.<br />Ceci afin de nous permettre d''améliorer notre réactivité et de vous apporter toute satisfaction dans notre réponse.<br /><br />Nous vous remercions de votre participation.<br /><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public<br /></p>');
INSERT INTO signalement_workflow_notifuser_3contents_config(id_task,subject,sender,message1,message2,message3) VALUES(91,'Signalement d''un incident','Mairie de Paris','<p>Nous avons bien reçu votre message mais les informations transmises sont insuffisantes ou inadaptées<br />et ne permettent pas à nos services d''y donner suite.<br />Avant de ne nous transmettre un nouveau message, nous vous invitons à vérifier si :<br /><br />- La localisation transmise est bien précise, en particulier dans un grand parc.<br />- L''incident se situe bien sur l''espace public municipal et non dans un espace privé.<br />- La description de la situation est précise.<br />- La qualité de la photo est correcte et adaptée.<br />- Une signalétique explicative n''est pas déjà mise en place autour de l''incident.<br />Ceci afin de nous permettre d''améliorer notre réactivité et de vous apporter toute satisfaction dans notre réponse.<br /><br />Nous vous remercions de votre participation.<br /><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public<br /></p>','<p>Nous avons bien reçu votre message mais les informations transmises sont insuffisantes ou inadaptées<br />et ne permettent pas à nos services d''y donner suite.<br />Avant de ne nous transmettre un nouveau message, nous vous invitons à vérifier si :<br /><br />- La localisation transmise est bien précise, en particulier dans un grand parc.<br />- L''incident se situe bien sur l''espace public municipal et non dans un espace privé.<br />- La description de la situation est précise.<br />- La qualité de la photo est correcte et adaptée.<br />- Une signalétique explicative n''est pas déjà mise en place autour de l''incident.<br />Ceci afin de nous permettre d''améliorer notre réactivité et de vous apporter toute satisfaction dans notre réponse.<br /><br />Nous vous remercions de votre participation.<br /><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public<br /></p>','<p>Nous avons bien reçu votre message mais les informations transmises sont insuffisantes ou inadaptées<br />et ne permettent pas à nos services d''y donner suite.<br />Avant de ne nous transmettre un nouveau message, nous vous invitons à vérifier si :<br /><br />- La localisation transmise est bien précise, en particulier dans un grand parc.<br />- L''incident se situe bien sur l''espace public municipal et non dans un espace privé.<br />- La description de la situation est précise.<br />- La qualité de la photo est correcte et adaptée.<br />- Une signalétique explicative n''est pas déjà mise en place autour de l''incident.<br />Ceci afin de nous permettre d''améliorer notre réactivité et de vous apporter toute satisfaction dans notre réponse.<br /><br />Nous vous remercions de votre participation.<br /><br />La Ville de Paris<br />Les services de la Mairie en charge de l''espace public<br /></p>');


-- Add right for message tracking management (US6 BO Signalement : Gestion du suivi des messages)
INSERT INTO core_admin_right (id_right, name, level_right, admin_url, description, is_updatable, plugin_name, id_feature_group, icon_url, documentation_url, id_order)
 VALUES ('MESSAGE_TRACKING_MANAGEMENT', 'module.workflow.signalement.adminFeature.messageTrackingManagement.name', 2, 'jsp/admin/plugins/workflow/modules/signalement/GetMessageTrackingManagement.jsp', 'module.workflow.signalement.adminFeature.messageTrackingManagement.description', 0, 'signalement', 'SIGNALEMENT', NULL, NULL, 1);

INSERT INTO core_user_right (id_right, id_user) VALUES ('MESSAGE_TRACKING_MANAGEMENT', 1);